import config from '@/stech.config'
import type { Comparison, Feature, Pricing } from '@/data/type'


/**
 * Data for the Pricing and Comparison components.
 *
 * @constant { Pricing[] } pricingData The pricing data.
 * @constant { Feature[] } featureData The feature data.
 * @constant { Comparison[] } comparisonData The comparison data.
 *
 * @since 3.0.0
 */
export const pricingData: Pricing[] = [
	{
		title: 'Basic',
		featured: true,
		description: 'Ideal for starter',
		features: [
			<><strong>Free</strong> Front Website</>,
			<><strong>Student</strong> Management</>,
			<><strong>Guardian</strong> Management</>,
			<><strong>Teacher</strong> Management</>,
			<><strong>Administrator</strong> Management</>,
			<><strong>Accountant</strong> Management</>,
			<><strong>Receptionist</strong> Management</>,
			<><strong>Librarian</strong> Management</>,
			<><strong>Attendance</strong> Management</>,
			<><strong>Fees</strong> Management</>,
			<><strong>Certificate</strong> Management</>,
			<><strong>Exam and Result</strong> Management</>,
			<><strong>Class and Subject</strong> Management</>,
			<><strong>Transport</strong> Management</>,
			<><strong>Hall</strong> Management</>,
			<><strong>SMS and Email</strong> Service</>,
			<><strong>Notice</strong> Service</>,
			<><strong>Chatting</strong> Service</>,
			<><strong>Dedicated</strong> Support</>,
		],
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/school-management/basic`,
		},
	},
	{
		title: 'Professional',
		description: 'Ideal for large institution',
		features: [
			<><strong>Free</strong> Front Website</>,
			<><strong>Student</strong> Management</>,
			<><strong>Guardian</strong> Management</>,
			<><strong>Teacher</strong> Management</>,
			<><strong>Administrator</strong> Management</>,
			<><strong>Accountant</strong> Management</>,
			<><strong>Receptionist</strong> Management</>,
			<><strong>Librarian</strong> Management</>,
			<><strong>Attendance</strong> Management</>,
			<><strong>Fees</strong> Management</>,
			<><strong>Certificate</strong> Management</>,
			<><strong>Exam and Result</strong> Management</>,
			<><strong>Class and Subject</strong> Management</>,
			<><strong>Transport</strong> Management</>,
			<><strong>Hall</strong> Management</>,
			<><strong>SMS and Email</strong> Service</>,
			<><strong>Notice</strong> Service</>,
			<><strong>Chatting</strong> Service</>,
			<><strong>Dedicated</strong> Support</>,
			<><strong>Android</strong> App</>,
		],
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/school-management/professional`,
		},
	},
	{
		title: 'Advanced',
		description: 'Ideal for large institution',
		features: [
			<><strong>Free</strong> Front Website</>,
			<><strong>Student</strong> Management</>,
			<><strong>Guardian</strong> Management</>,
			<><strong>Teacher</strong> Management</>,
			<><strong>Administrator</strong> Management</>,
			<><strong>Accountant</strong> Management</>,
			<><strong>Receptionist</strong> Management</>,
			<><strong>Librarian</strong> Management</>,
			<><strong>Attendance</strong> Management</>,
			<><strong>Fees</strong> Management</>,
			<><strong>Certificate</strong> Management</>,
			<><strong>Exam and Result</strong> Management</>,
			<><strong>Class and Subject</strong> Management</>,
			<><strong>Transport</strong> Management</>,
			<><strong>Hall</strong> Management</>,
			<><strong>SMS and Email</strong> Service</>,
			<><strong>Notice</strong> Service</>,
			<><strong>Chatting</strong> Service</>,
			<><strong>Dedicated</strong> Support</>,
			<><strong>Android</strong> App</>,
			<><strong>iOS</strong> App</>,
		],
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/school-management/advanced`,
		},
	},
]
export const featureData: Feature[] = [
	{
		title: 'Front Website',
		features: {
			home: 'Homepage',
			slider: 'Image Slider',
			gallery: 'Image and Video Gallery',
			message: 'Message from Principal',
			result: 'Result Page',
			admission: 'Admission Page',
			mission: 'Mission and Vision Page',
			notice: 'Notice Board',
			about: 'About Page',
			contact: 'Contact Page',
			map: 'Google Map',
			seo: 'SEO Friendly',
			analytics: 'Google Analytics',
			google: 'Google Search Engine Tool',
			bing: 'Bing Search Engine Tool',
		},
	},
	{
		title: 'Student Management',
		features: {
			student: 'Student Registration',
			studentProfile: 'Student Profile',
			studentSibling: 'Student Sibling Information',
			studentData: 'Student Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Guardian Management',
		features: {
			guardian: 'Guardian Registration',
			guardianList: 'Guardian List',
			guardianProfile: 'Guardian Profile',
			guardianStudent: 'Guardian Student Information',
			guardianData: 'Guardian Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Teacher Management',
		features: {
			teacher: 'Teacher Add, Edit, and Delete',
			teacherProfile: 'Teacher Profile',
			teacherAttendance: 'Teacher Attendance',
			teacherAllocation: 'Teacher Allocation',
			teacherData: 'Teacher Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Other Management',
		features: {
			admin: 'Admin Management',
			accountant: 'Accountant Management',
			receptionist: 'Receptionist Management',
			librarian: 'Librarian Management',
		},
	},
	{
		title: 'Fees Management',
		features: {
			fees: 'Fees Management',
			feesPayment: 'Fees Payment Processing',
			feesAccount: 'Fees Account Management',
			feesData: 'Fees Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Certificate Management',
		features: {
			certificate: 'Certificate Creation, Edit, and Delete',
			certificateData: 'Certificate Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Exam and Result Management',
		features: {
			exam: 'Exam Management',
			examList: 'Exam List',
			examRoutine: 'Exam Routine',
			examSchedule: 'Exam Schedule',
			examData: 'Exam Data Export, Import, Print, and Backup',
			resultPublish: 'Result Publish',
			resultArchive: 'Result Archive',
			resultBroadcast: 'Result Broadcast',
			resultData: 'Result Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Class and Subject Management',
		features: {
			class: 'Class Management',
			classList: 'Class List',
			classAllocation: 'Class Allocation',
			classSchedule: 'Class Schedule',
			classTeacher: 'Class Teacher Allocation',
			classData: 'Class Data Export, Import, Print, and Backup',
			subject: 'Subject Management',
			subjectList: 'Subject List',
			subjectAllocation: 'Subject Allocation',
			subjectData: 'Subject Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Transport Management',
		features: {
			transport: 'Transport Management',
			transportRoute: 'Transport Route',
			transportSchedule: 'Transport Schedule',
			transportDriver: 'Transport Driver Allocation',
			transportStudent: 'Transport Student Allocation',
			transportData: 'Transport Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Hall Management',
		features: {
			hall: 'Hall Management',
			hallList: 'Hall List',
			hallRoom: 'Hall Room Allocation',
			hallProvost: 'Hall Provost Allocation',
			hallTeacher: 'Hall House Teacher Allocation',
			hallData: 'Hall Data Export, Import, Print, and Backup',
		},
	},
	{
		title: 'Service',
		features: {
			sms: 'SMS Service',
			email: 'Email Service',
			chat: 'Chatting Service',
			support: 'Dedicated Support',
		},
	},
	{
		title: 'Mobile App',
		features: {
			android: 'Android App',
			ios: 'iOS App',
		},
	},
]
export const comparisonData: Comparison[] = [
	{
		title: 'Basic',
		description: 'Ideal for starter',
		features: {
			home: true,
			slider: true,
			gallery: true,
			message: true,
			result: true,
			admission: true,
			mission: true,
			notice: true,
			about: true,
			contact: true,
			map: true,
			seo: true,
			analytics: true,
			google: true,
			bing: true,
			student: true,
			studentProfile: true,
			studentSibling: true,
			studentData: true,
			guardian: true,
			guardianList: true,
			guardianProfile: true,
			guardianStudent: true,
			guardianData: true,
			teacher: true,
			teacherProfile: true,
			teacherAttendance: true,
			teacherAllocation: true,
			teacherData: true,
			admin: true,
			accountant: true,
			receptionist: true,
			librarian: true,
			fees: true,
			feesPayment: true,
			feesAccount: true,
			feesData: true,
			certificate: true,
			certificateData: true,
			exam: true,
			examList: true,
			examRoutine: true,
			examSchedule: true,
			examData: true,
			resultPublish: true,
			resultArchive: true,
			resultBroadcast: true,
			resultData: true,
			class: true,
			classList: true,
			classAllocation: true,
			classSchedule: true,
			classTeacher: true,
			classData: true,
			subject: true,
			subjectList: true,
			subjectAllocation: true,
			subjectData: true,
			transport: true,
			transportRoute: true,
			transportSchedule: true,
			transportDriver: true,
			transportStudent: true,
			transportData: true,
			hall: true,
			hallList: true,
			hallRoom: true,
			hallProvost: true,
			hallTeacher: true,
			hallData: true,
			sms: true,
			email: true,
			chat: true,
			support: true,
			android: false,
			ios: false,
		},
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/school-management/basic`,
		},
	},
	{
		title: 'Professional',
		description: 'Ideal for large institution',
		features: {
			home: true,
			slider: true,
			gallery: true,
			message: true,
			result: true,
			admission: true,
			mission: true,
			notice: true,
			about: true,
			contact: true,
			map: true,
			seo: true,
			analytics: true,
			google: true,
			bing: true,
			student: true,
			studentProfile: true,
			studentSibling: true,
			studentData: true,
			guardian: true,
			guardianList: true,
			guardianProfile: true,
			guardianStudent: true,
			guardianData: true,
			teacher: true,
			teacherProfile: true,
			teacherAttendance: true,
			teacherAllocation: true,
			teacherData: true,
			admin: true,
			accountant: true,
			receptionist: true,
			librarian: true,
			fees: true,
			feesPayment: true,
			feesAccount: true,
			feesData: true,
			certificate: true,
			certificateData: true,
			exam: true,
			examList: true,
			examRoutine: true,
			examSchedule: true,
			examData: true,
			resultPublish: true,
			resultArchive: true,
			resultBroadcast: true,
			resultData: true,
			class: true,
			classList: true,
			classAllocation: true,
			classSchedule: true,
			classTeacher: true,
			classData: true,
			subject: true,
			subjectList: true,
			subjectAllocation: true,
			subjectData: true,
			transport: true,
			transportRoute: true,
			transportSchedule: true,
			transportDriver: true,
			transportStudent: true,
			transportData: true,
			hall: true,
			hallList: true,
			hallRoom: true,
			hallProvost: true,
			hallTeacher: true,
			hallData: true,
			sms: true,
			email: true,
			chat: true,
			support: true,
			android: true,
			ios: false,
		},
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/school-management/professional`,
		},
	},
	{
		title: 'Advanced',
		description: 'Ideal for large institution',
		features: {
			home: true,
			slider: true,
			gallery: true,
			message: true,
			result: true,
			admission: true,
			mission: true,
			notice: true,
			about: true,
			contact: true,
			map: true,
			seo: true,
			analytics: true,
			google: true,
			bing: true,
			student: true,
			studentProfile: true,
			studentSibling: true,
			studentData: true,
			guardian: true,
			guardianList: true,
			guardianProfile: true,
			guardianStudent: true,
			guardianData: true,
			teacher: true,
			teacherProfile: true,
			teacherAttendance: true,
			teacherAllocation: true,
			teacherData: true,
			admin: true,
			accountant: true,
			receptionist: true,
			librarian: true,
			fees: true,
			feesPayment: true,
			feesAccount: true,
			feesData: true,
			certificate: true,
			certificateData: true,
			exam: true,
			examList: true,
			examRoutine: true,
			examSchedule: true,
			examData: true,
			resultPublish: true,
			resultArchive: true,
			resultBroadcast: true,
			resultData: true,
			class: true,
			classList: true,
			classAllocation: true,
			classSchedule: true,
			classTeacher: true,
			classData: true,
			subject: true,
			subjectList: true,
			subjectAllocation: true,
			subjectData: true,
			transport: true,
			transportRoute: true,
			transportSchedule: true,
			transportDriver: true,
			transportStudent: true,
			transportData: true,
			hall: true,
			hallList: true,
			hallRoom: true,
			hallProvost: true,
			hallTeacher: true,
			hallData: true,
			sms: true,
			email: true,
			chat: true,
			support: true,
			android: true,
			ios: true,
		},
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/school-management/advanced`,
		},
	},
]
