import type { Comparison, Feature, Pricing } from '@/app/_data/type'


/**
 * Data for the Pricing and Comparison components.
 *
 * @constant { Pricing[] } pricingData The pricing data.
 * @constant { Feature[] } featureData The feature data.
 * @constant { Comparison[] } comparisonData The comparison data.
 *
 * @since 3.0.0
 */
export const pricingData: Pricing[] = [
	{
		title: 'Personal and Portfolio Website (Static)',
		featured: true,
		price: {
			bdt: 8000,
			usd: 80,
		},
		renew: {
			bdt: 3200,
			usd: 32,
		},
		period: 0,
		description: 'Ideal for simple personal and portfolio website',
		features: [
			<><strong>1</strong> Static Website</>,
			<><strong>3GB NVMe SSD</strong> Storage</>,
			<><strong>60GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/personal-static',
		},
	},
	{
		title: 'Personal and Portfolio Website (with Blog)',
		featured: true,
		price: {
			bdt: 10000,
			usd: 100,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for personal and portfolio website with blog',
		features: [
			<><strong>1</strong> CMS Website with Blog</>,
			<><strong>5GB NVMe SSD</strong> Storage</>,
			<><strong>100GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/personal-blog',
		},
	},
	{
		title: 'Personal and Portfolio Website (React.js)',
		featured: true,
		price: {
			bdt: 15000,
			usd: 150,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for personal and portfolio website',
		features: [
			<><strong>1</strong> React.js Website</>,
			<><strong>5GB NVMe SSD</strong> Storage</>,
			<><strong>100GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/personal-blog',
		},
	},
	{
		title: 'Company and Organization Website',
		featured: true,
		price: {
			bdt: 10000,
			usd: 100,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for low visitor company and organization website with blog',
		features: [
			<><strong>1</strong> CMS Website with Blog</>,
			<><strong>5GB NVMe SSD</strong> Storage</>,
			<><strong>100GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/organization',
		},
	},
	{
		title: 'Newspaper and Magazine Website',
		featured: true,
		price: {
			bdt: 10000,
			usd: 100,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for low visitor newspaper and magazine website',
		features: [
			<><strong>1</strong> CMS Website</>,
			<><strong>5GB NVMe SSD</strong> Storage</>,
			<><strong>100GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/newspaper',
		},
	},
	{
		title: 'Ecommerce Website (with Blog)',
		featured: true,
		price: {
			bdt: 10000,
			usd: 100,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for low visitor ecommerce website with blog',
		features: [
			<><strong>1</strong> CMS Website with Blog</>,
			<><strong>5GB NVMe SSD</strong> Storage</>,
			<><strong>100GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/ecommerce',
		},
	},
]
export const featureData: Feature[] = [
	{
		title: 'Website',
		features: {
			blog: 'Has Blog',
			page: 'Number of Page',
			content: 'Content Upload',
			contact: 'Contact Form',
			seo: 'SEO Friendly',
			google: 'Google Search Tool',
			bing: 'Bing Search Tool',
			analytics: 'Google Analytics',
		}
	},
	{
		title: 'General',
		features: {
			storage: 'Storage',
			bandwidth: 'Bandwidth',
			domain: 'Addon Domain',
			subdomain: 'Subdomain',
			parked: 'Parked Domain',
			email: 'Email Account',
			ftp: 'FTP Account',
			database: 'Database',
			ssl: 'SSL Certificate',
			uptime: 'Uptime',
			panel: 'Control Panel',
		}
	},
	{
		title: 'Performance',
		features: {
			ram: 'RAM',
			entryProcess: 'Entry Process',
			process: 'Number of Processes',
			io: 'IO',
			iops: 'IOPS',
		}
	},
	{
		title: 'System',
		features: {
			os: 'Operating System',
			distro: 'Distribution',
			architecture: 'Architecture',
		},
	},
	{
		title: 'Programming Language and Manager',
		features: {
			php: 'PHP',
			pear: 'PEAR',
			nodejs: 'Node.js',
			npm: 'NPM',
			python: 'Python',
			pip: 'PIP',
			ruby: 'Ruby',
			gem: 'GEM',
			perl: 'Perl',
			cpan: 'CPAN',
			mysql: 'MySQL',
			mariadb: 'MariaDB',
			phpmyadmin: 'phpMyAdmin',
		},
	},
	{
		title: 'Development Tool',
		features: {
			terminal: 'Terminal',
			ssh: 'SSH',
			git: 'Git',
		},
	},
	{
		title: 'Other Tool',
		features: {
			metrics: 'Metrics',
			security: 'Security',
			virusScanner: 'Virus Scanner',
			softaculous: 'Softaculous',
			wordpress: 'WordPress',
			backup: 'Backup',
		},
	},
]
export const comparisonData: Comparison[] = [
	{
		title: 'Personal and Portfolio Website (Static)',
		price: {
			bdt: 8000,
			usd: 80,
		},
		renew: {
			bdt: 3200,
			usd: 32,
		},
		period: 0,
		description: 'Ideal for simple personal and portfolio website',
		features: {
			blog: false,
			page: '1',
			content: 'Client Provided',
			contact: true,
			seo: true,
			google: true,
			bing: true,
			analytics: true,
			storage: '3GB',
			bandwidth: '60GB',
			domain: '1',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/personal-static',
		},
	},
	{
		title: 'Personal and Portfolio Website (with Blog)',
		price: {
			bdt: 10000,
			usd: 100,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for personal and portfolio website with blog',
		features: {
			blog: true,
			page: '1',
			content: 'Client Provided',
			contact: true,
			seo: true,
			google: true,
			bing: true,
			analytics: true,
			storage: '5GB',
			bandwidth: '100GB',
			domain: '1',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/personal-blog',
		},
	},
	{
		title: 'Personal and Portfolio Website (React.js)',
		price: {
			bdt: 15000,
			usd: 150,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for personal and portfolio website',
		features: {
			blog: false,
			page: '1',
			content: 'Client Provided',
			contact: true,
			seo: true,
			google: true,
			bing: true,
			analytics: true,
			storage: '5GB',
			bandwidth: '100GB',
			domain: '1',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/personal-blog',
		},
	},
	{
		title: 'Company and Organization Website',
		price: {
			bdt: 10000,
			usd: 100,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for low visitor company and organization website with blog',
		features: {
			blog: true,
			page: '1',
			content: 'Client Provided',
			contact: true,
			seo: true,
			google: true,
			bing: true,
			analytics: true,
			storage: '5GB',
			bandwidth: '100GB',
			domain: '1',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/organization',
		},
	},
	{
		title: 'Newspaper and Magazine Website',
		price: {
			bdt: 10000,
			usd: 100,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for low visitor newspaper and magazine website',
		features: {
			blog: false,
			page: '1',
			content: 'Client Provided',
			contact: true,
			seo: true,
			google: true,
			bing: true,
			analytics: true,
			storage: '5GB',
			bandwidth: '100GB',
			domain: '1',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/newspaper',
		},
	},
	{
		title: 'Ecommerce Website (with Blog)',
		price: {
			bdt: 10000,
			usd: 100,
		},
		renew: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for low visitor ecommerce website with blog',
		features: {
			blog: true,
			page: '1',
			content: 'Client Provided',
			contact: true,
			seo: true,
			google: true,
			bing: true,
			analytics: true,
			storage: '5GB',
			bandwidth: '100GB',
			domain: '1',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/readymade-website/ecommerce',
		},
	},
]
