import config from '@/stech.config'
import type { Comparison, Feature, Pricing } from '@/data/type'


/**
 * Data for the Pricing and Comparison components.
 *
 * @constant { Pricing[] } pricingData The pricing data.
 * @constant { Feature[] } featureData The feature data.
 * @constant { Comparison[] } comparisonData The comparison data.
 *
 * @since 3.0.0
 */
export const pricingData: Pricing[] = [
	{
		title: '25GB',
		featured: false,
		price: {
			bdt: 3000,
			usd: 30,
		},
		period: 1,
		description: 'Ideal for medium traffic website',
		features: [
			<><strong>25GB NVMe SSD</strong> Storage</>,
			<><strong>1000GB (1TB)</strong> Bandwidth</>,
			<><strong>2GB</strong> Dedicated RAM</>,
			<><strong>2</strong> CPU/Processor</>,
			<><strong>1</strong> Dedicated IP</>,
			<><strong>Management</strong> Service</>,
			<><strong>SSL</strong> Certificate</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>WHM</strong> as Hosting Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>USA, BD (BDIX), or SG</strong> Server</>,
		],
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/managed-vps/25gb`,
		},
	},
	{
		title: '40GB',
		featured: true,
		price: {
			bdt: 4000,
			usd: 40,
		},
		period: 1,
		description: 'Ideal for high traffic website',
		features: [
			<><strong>40GB NVMe SSD</strong> Storage</>,
			<><strong>2000GB (2TB)</strong> Bandwidth</>,
			<><strong>4GB</strong> Dedicated RAM</>,
			<><strong>4</strong> CPU/Processor</>,
			<><strong>1</strong> Dedicated IP</>,
			<><strong>Management</strong> Service</>,
			<><strong>SSL</strong> Certificate</>,
			<><strong>Backup</strong> Plugin</>,
			<><strong>Backup</strong> Storage</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>WHM</strong> as Hosting Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>USA, BD (BDIX), or SG</strong> Server</>,
		],
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/managed-vps/40gb`,
		},
	},
	{
		title: '60GB',
		featured: false,
		price: {
			bdt: 5000,
			usd: 50,
		},
		period: 1,
		description: 'Ideal for high traffic website',
		features: [
			<><strong>60GB NVMe SSD</strong> Storage</>,
			<><strong>3000GB (3TB)</strong> Bandwidth</>,
			<><strong>6GB</strong> Dedicated RAM</>,
			<><strong>4</strong> CPU/Processor</>,
			<><strong>2</strong> Dedicated IP</>,
			<><strong>Management</strong> Service</>,
			<><strong>SSL</strong> Certificate</>,
			<><strong>Backup</strong> Plugin</>,
			<><strong>Backup</strong> Storage</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>WHM</strong> as Hosting Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>USA, BD (BDIX), or SG</strong> Server</>,
		],
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/managed-vps/60gb`,
		},
	},
	{
		title: '100GB',
		featured: false,
		price: {
			bdt: 6500,
			usd: 65,
		},
		period: 1,
		description: 'Ideal for high traffic website',
		features: [
			<><strong>100GB NVMe SSD</strong> Storage</>,
			<><strong>10000GB (10TB)</strong> Bandwidth</>,
			<><strong>10GB</strong> Dedicated RAM</>,
			<><strong>6</strong> CPU/Processor</>,
			<><strong>2</strong> Dedicated IP</>,
			<><strong>Management</strong> Service</>,
			<><strong>SSL</strong> Certificate</>,
			<><strong>Backup</strong> Plugin</>,
			<><strong>Backup</strong> Storage</>,
			<><strong>cPanel</strong> as Control Panel</>,
			<><strong>WHM</strong> as Hosting Control Panel</>,
			<><strong>Softaculous</strong> Software Installer</>,
			<><strong>USA, BD (BDIX), or SG</strong> Server</>,
		],
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/managed-vps/100gb`,
		},
	},
]
export const featureData: Feature[] = [
	{
		title: 'General',
		features: {
			storage: 'Storage',
			bandwidth: 'Bandwidth',
			ip: 'Dedicated IP',
			backupPlugin: 'Backup Plugin',
			backupStorage: 'Backup Storage',
			domain: 'Addon Domain',
			subdomain: 'Subdomain',
			parked: 'Parked Domain',
			email: 'Email Account',
			ftp: 'FTP Account',
			database: 'Database',
			ssl: 'SSL Certificate',
			uptime: 'Uptime',
			panel: 'Control Panel',
			whm: 'Hosting Control Panel',
		}
	},
	{
		title: 'Performance',
		features: {
			ram: 'RAM',
			cpu: 'CPU/Processor',
		}
	},
	{
		title: 'System',
		features: {
			os: 'Operating System',
			distro: 'Distribution',
			architecture: 'Architecture',
		},
	},
	{
		title: 'Programming Language and Manager',
		features: {
			php: 'PHP',
			pear: 'PEAR',
			nodejs: 'Node.js',
			npm: 'NPM',
			python: 'Python',
			pip: 'PIP',
			ruby: 'Ruby',
			gem: 'GEM',
			perl: 'Perl',
			cpan: 'CPAN',
			mysql: 'MySQL',
			mariadb: 'MariaDB',
			phpmyadmin: 'phpMyAdmin',
		},
	},
	{
		title: 'Development Tool',
		features: {
			terminal: 'Terminal',
			ssh: 'SSH',
			git: 'Git',
		},
	},
	{
		title: 'Other Tool',
		features: {
			metrics: 'Metrics',
			security: 'Security',
			virusScanner: 'Virus Scanner',
			softaculous: 'Softaculous',
			wordpress: 'WordPress',
			backup: 'Backup',
		},
	},
]
export const comparisonData: Comparison[] = [
	{
		title: '25GB',
		price: {
			bdt: 3000,
			usd: 30,
		},
		period: 1,
		description: 'Ideal for medium traffic website',
		features: {
			storage: '25GB',
			bandwidth: '1000GB (1TB)',
			ip: '1',
			backupPlugin: false,
			backupStorage: false,
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			whm: 'WHM',
			ram: '2GB',
			cpu: '2',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: false,
		},
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/managed-vps/25gb`,
		},
	},
	{
		title: '40GB',
		price: {
			bdt: 4000,
			usd: 40,
		},
		period: 1,
		description: 'Ideal for high traffic website',
		features: {
			storage: '40GB',
			bandwidth: '2000GB (2TB)',
			ip: '1',
			backupPlugin: true,
			backupStorage: true,
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			whm: 'WHM',
			ram: '4GB',
			cpu: '4',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/managed-vps/40gb`,
		},
	},
	{
		title: '60GB',
		price: {
			bdt: 5000,
			usd: 50,
		},
		period: 1,
		description: 'Ideal for high traffic website',
		features: {
			storage: '60GB',
			bandwidth: '3000GB (3TB)',
			ip: '2',
			backupPlugin: true,
			backupStorage: true,
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			whm: 'WHM',
			ram: '6GB',
			cpu: '4',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/managed-vps/60gb`,
		},
	},
	{
		title: '100GB',
		price: {
			bdt: 6500,
			usd: 65,
		},
		period: 1,
		description: 'Ideal for high traffic website',
		features: {
			storage: '100GB',
			bandwidth: '10000GB (10TB)',
			ip: '2',
			backupPlugin: true,
			backupStorage: true,
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			whm: 'WHM',
			ram: '10GB',
			cpu: '6',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: `${ config.info.cp }/store/managed-vps/100gb`,
		},
	},
]
