import { Comparison, Feature, Pricing } from '@/app/_data/type'

export const pricingData: Pricing[] = [
	{
		title: '3GB',
		featured: true,
		price: {
			bdt: 3200,
			usd: 32,
		},
		period: 0,
		description: 'Ideal for low traffic website',
		features: [
			<><strong>3GB NVMe SSD</strong> Storage</>,
			<><strong>60GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/3gb',
		},
	},
	{
		title: '5GB',
		price: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for low traffic website',
		features: [
			<><strong>5GB NVMe SSD</strong> Storage</>,
			<><strong>100GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/5gb',
		},
	},
	{
		title: '10GB',
		price: {
			bdt: 6500,
			usd: 65,
		},
		period: 0,
		description: 'Ideal for low traffic business website',
		features: [
			<><strong>10GB NVMe SSD</strong> Storage</>,
			<><strong>200GB</strong> Bandwidth</>,
			<><strong>2</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/10gb',
		},
	},
	{
		title: '15GB',
		price: {
			bdt: 9500,
			usd: 95,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: [
			<><strong>15GB NVMe SSD</strong> Storage</>,
			<><strong>300GB</strong> Bandwidth</>,
			<><strong>5</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/15gb',
		},
	},
	{
		title: '20GB',
		price: {
			bdt: 12000,
			usd: 120,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: [
			<><strong>20GB NVMe SSD</strong> Storage</>,
			<><strong>400GB</strong> Bandwidth</>,
			<><strong>Unlimited</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/20gb',
		},
	},
	{
		title: '25GB',
		price: {
			bdt: 14500,
			usd: 145,
		},
		period: 1,
		description: 'Ideal for medium traffic business website',
		features: [
			<><strong>25GB NVMe SSD</strong> Storage</>,
			<><strong>500GB</strong> Bandwidth</>,
			<><strong>Unlimited</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/25gb'
		},
	},
	{
		title: 'Unlimited-A',
		price: {
			bdt: 10000,
			usd: 100,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: [
			<><strong>Unlimited NVMe SSD</strong> Storage</>,
			<><strong>200GB</strong> Bandwidth</>,
			<><strong>1</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/ua',
		},
	},
	{
		title: 'Unlimited-B',
		price: {
			bdt: 20000,
			usd: 200,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: [
			<><strong>Unlimited NVMe SSD</strong> Storage</>,
			<><strong>Unlimited</strong> Bandwidth</>,
			<><strong>2</strong> Domain</>,
			<><strong>Unlimited</strong> Subdomain and Parked Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Free</strong> SSL Certificate</>,
			<><strong>99.9%</strong> Uptime</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/ub',
		},
	},
]
export const featureData: Feature[] = [
	{
		title: 'General',
		features: {
			storage: 'Storage',
			bandwidth: 'Bandwidth',
			domain: 'Addon Domain',
			subdomain: 'Subdomain',
			parked: 'Parked Domain',
			email: 'Email Account',
			ftp: 'FTP Account',
			database: 'Database',
			ssl: 'SSL Certificate',
			uptime: 'Uptime',
			panel: 'Control Panel',
		}
	},
	{
		title: 'Performance',
		features: {
			ram: 'RAM',
			entryProcess: 'Entry Process',
			process: 'Number of Processes',
			io: 'IO',
			iops: 'IOPS',
		}
	},
	{
		title: 'System',
		features: {
			os: 'Operating System',
			distro: 'Distribution',
			architecture: 'Architecture',
		},
	},
	{
		title: 'Programming Language and Manager',
		features: {
			php: 'PHP',
			pear: 'PEAR',
			nodejs: 'Node.js',
			npm: 'NPM',
			python: 'Python',
			pip: 'PIP',
			ruby: 'Ruby',
			gem: 'GEM',
			perl: 'Perl',
			cpan: 'CPAN',
			mysql: 'MySQL',
			mariadb: 'MariaDB',
			phpmyadmin: 'phpMyAdmin',
		},
	},
	{
		title: 'Development Tool',
		features: {
			terminal: 'Terminal',
			ssh: 'SSH',
			git: 'Git',
		},
	},
	{
		title: 'Other Tool',
		features: {
			metrics: 'Metrics',
			security: 'Security',
			virusScanner: 'Virus Scanner',
			softaculous: 'Softaculous',
			wordpress: 'WordPress',
			backup: 'Backup',
		},
	},
]
export const comparisonData: Comparison[] = [
	{
		title: '3GB',
		price: {
			bdt: 3200,
			usd: 32,
		},
		period: 0,
		description: 'Ideal for low traffic website',
		features: {
			storage: '3GB',
			bandwidth: '60GB',
			domain: '1',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/3gb',
		},
	},
	{
		title: '5GB',
		price: {
			bdt: 4000,
			usd: 40,
		},
		period: 0,
		description: 'Ideal for low traffic website',
		features: {
			storage: '5GB',
			bandwidth: '100GB',
			domain: '1',
			subdomain: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/5gb',
		},
	},
	{
		title: '10GB',
		price: {
			bdt: 5500,
			usd: 55,
		},
		period: 0,
		description: 'Ideal for low traffic business website',
		features: {
			storage: '10GB',
			bandwidth: '200GB',
			domain: '2',
			subdomain: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/10gb',
		},
	},
	{
		title: '15GB',
		price: {
			bdt: 9500,
			usd: 95,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: {
			storage: '15GB',
			bandwidth: '300GB',
			domain: '5',
			subdomain: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/15gb',
		},
	},
	{
		title: '20GB',
		price: {
			bdt: 12000,
			usd: 120,
		},
		period: 0,
		description: 'Ideal for low traffic business website',
		features: {
			storage: '20GB',
			bandwidth: '400GB',
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/20gb',
		},
	},
	{
		title: '25GB',
		price: {
			bdt: 14500,
			usd: 145,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: {
			storage: '25GB',
			bandwidth: '500GB',
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/25gb',
		},
	},
	{
		title: 'Unlimited-A',
		price: {
			bdt: 10000,
			usd: 100,
		},
		period: 0,
		description: 'Ideal for low traffic business website',
		features: {
			storage: 'Unlimited',
			bandwidth: '200GB',
			domain: '1',
			subdomain: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/ua',
		},
	},
	{
		title: 'Unlimited-B',
		price: {
			bdt: 20000,
			usd: 200,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: {
			storage: 'Unlimited',
			bandwidth: 'Unlimited',
			domain: '2',
			subdomain: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: true,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/shared-hosting/ub',
		},
	},
]