import type { Feature, Pricing } from '@/data/type'


/**
 * Data for the Pricing and Comparison components.
 *
 * @constant { Pricing[] } pricingData The pricing data.
 * @constant { Feature[] } featureData The feature data.
 * @constant { Comparison[] } comparisonData The comparison data.
 *
 * @since 3.0.0
 */
export const pricingData: Pricing[] = [
	{
		title: '10GB',
		price: {
			bdt: 7000,
			usd: 70,
		},
		period: 0,
		description: 'Ideal for starting hosting service business',
		features: [
			<><strong>10GB NVMe SSD</strong> Storage</>,
			<><strong>200GB</strong> Bandwidth</>,
			<><strong>5 cPanel</strong> Account</>,
			<><strong>Unlimited</strong> Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Unlimited Free</strong> SSL Certificate</>,
			<><strong>cPanel and WHM</strong> Control Panel</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/10gb',
		},
	},
	{
		title: '20GB',
		price: {
			bdt: 13000,
			usd: 130,
		},
		period: 0,
		description: 'Ideal for starting hosting service business',
		features: [
			<><strong>20GB NVMe SSD</strong> Storage</>,
			<><strong>400GB</strong> Bandwidth</>,
			<><strong>10 cPanel</strong> Account</>,
			<><strong>Unlimited</strong> Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Unlimited Free</strong> SSL Certificate</>,
			<><strong>cPanel and WHM</strong> Control Panel</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/20gb',
		},
	},
	{
		title: '25GB',
		price: {
			bdt: 16000,
			usd: 160,
		},
		period: 0,
		description: 'Ideal for starting hosting service business',
		features: [
			<><strong>25GB NVMe SSD</strong> Storage</>,
			<><strong>500GB</strong> Bandwidth</>,
			<><strong>12 cPanel</strong> Account</>,
			<><strong>Unlimited</strong> Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Unlimited Free</strong> SSL Certificate</>,
			<><strong>cPanel and WHM</strong> Control Panel</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/25gb',
		},
	},
	{
		title: '30GB',
		price: {
			bdt: 19000,
			usd: 190,
		},
		period: 0,
		description: 'Ideal for starting hosting service business',
		features: [
			<><strong>30GB NVMe SSD</strong> Storage</>,
			<><strong>600GB</strong> Bandwidth</>,
			<><strong>15 cPanel</strong> Account</>,
			<><strong>Unlimited</strong> Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Unlimited Free</strong> SSL Certificate</>,
			<><strong>cPanel and WHM</strong> Control Panel</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/30gb',
		},
	},
	{
		title: '50GB',
		price: {
			bdt: 30000,
			usd: 300,
		},
		period: 0,
		description: 'Ideal for starting hosting service business',
		features: [
			<><strong>50GB NVMe SSD</strong> Storage</>,
			<><strong>1000GB (1TB)</strong> Bandwidth</>,
			<><strong>30 cPanel</strong> Account</>,
			<><strong>Unlimited</strong> Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Unlimited Free</strong> SSL Certificate</>,
			<><strong>cPanel and WHM</strong> Control Panel</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/50gb',
		},
	},
	{
		title: '100GB',
		price: {
			bdt: 50000,
			usd: 500,
		},
		period: 0,
		description: 'Ideal for starting hosting service business',
		features: [
			<><strong>100GB NVMe SSD</strong> Storage</>,
			<><strong>2000GB (2TB)</strong> Bandwidth</>,
			<><strong>50 cPanel</strong> Account</>,
			<><strong>Unlimited</strong> Domain</>,
			<><strong>Unlimited</strong> Email Account, FTP, and Database</>,
			<><strong>Unlimited Free</strong> SSL Certificate</>,
			<><strong>cPanel and WHM</strong> Control Panel</>,
		],
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/100gb',
		},
	},
]
export const featureData: Feature[] = [
	{
		title: 'General',
		features: {
			storage: 'Storage',
			bandwidth: 'Bandwidth',
			domain: 'Addon Domain',
			subdomain: 'Subdomain',
			parked: 'Parked Domain',
			email: 'Email Account',
			ftp: 'FTP Account',
			database: 'Database',
			ssl: 'SSL Certificate',
			uptime: 'Uptime',
			panel: 'Control Panel',
		}
	},
	{
		title: 'Reseller',
		features: {
			cpanel: 'cPanel',
			whm: 'WHM by cPanel',
			whmcs: 'WHMCS',
		},
	},
	{
		title: 'Performance',
		features: {
			ram: 'RAM',
			entryProcess: 'Entry Process',
			process: 'Number of Processes',
			io: 'IO',
			iops: 'IOPS',
		}
	},
	{
		title: 'System',
		features: {
			os: 'Operating System',
			distro: 'Distribution',
			architecture: 'Architecture',
		},
	},
	{
		title: 'Programming Language and Manager',
		features: {
			php: 'PHP',
			pear: 'PEAR',
			nodejs: 'Node.js',
			npm: 'NPM',
			python: 'Python',
			pip: 'PIP',
			ruby: 'Ruby',
			gem: 'GEM',
			perl: 'Perl',
			cpan: 'CPAN',
			mysql: 'MySQL',
			mariadb: 'MariaDB',
			phpmyadmin: 'phpMyAdmin',
		},
	},
	{
		title: 'Development Tool',
		features: {
			terminal: 'Terminal',
			ssh: 'SSH',
			git: 'Git',
		},
	},
	{
		title: 'Other Tool',
		features: {
			metrics: 'Metrics',
			security: 'Security',
			virusScanner: 'Virus Scanner',
			softaculous: 'Softaculous',
			wordpress: 'WordPress',
			backup: 'Backup',
		},
	},
]
export const comparisonData = [
	{
		title: '10GB',
		price: {
			bdt: 7000,
			usd: 70,
		},
		period: 0,
		description: 'Ideal for low traffic business website',
		features: {
			storage: '10GB',
			bandwidth: '200GB',
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			cpanel: 5,
			whm: true,
			whmcs: false,
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/10gb',
		},
	},
	{
		title: '20GB',
		price: {
			bdt: 13000,
			usd: 130,
		},
		period: 0,
		description: 'Ideal for low traffic website',
		features: {
			storage: '20GB',
			bandwidth: '400GB',
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			cpanel: 10,
			whm: true,
			whmcs: false,
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/20gb',
		},
	},
	{
		title: '25GB',
		price: {
			bdt: 16000,
			usd: 160,
		},
		period: 0,
		description: 'Ideal for low traffic business website',
		features: {
			storage: '25GB',
			bandwidth: '500GB',
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			cpanel: 12,
			whm: true,
			whmcs: false,
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/25gb',
		},
	},
	{
		title: '30GB',
		price: {
			bdt: 19000,
			usd: 190,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: {
			storage: '30GB',
			bandwidth: '600GB',
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			cpanel: 15,
			whm: true,
			whmcs: false,
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/30gb',
		},
	},
	{
		title: '50GB',
		price: {
			bdt: 30000,
			usd: 300,
		},
		period: 0,
		description: 'Ideal for low traffic business website',
		features: {
			storage: '50GB',
			bandwidth: '1000GB (1T)',
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			cpanel: 30,
			whm: true,
			whmcs: false,
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/50gb',
		},
	},
	{
		title: '100GB',
		price: {
			bdt: 50000,
			usd: 500,
		},
		period: 0,
		description: 'Ideal for medium traffic business website',
		features: {
			storage: '100GB',
			bandwidth: '2000GB (2TB)',
			domain: 'Unlimited',
			subdomain: 'Unlimited',
			parked: 'Unlimited',
			email: 'Unlimited',
			ftp: 'Unlimited',
			database: 'Unlimited',
			ssl: true,
			uptime: '99.9%',
			panel: 'cPanel',
			cpanel: 50,
			whm: true,
			whmcs: false,
			ram: '1GB',
			entryProcess: '30',
			process: '120',
			io: '20MBPS',
			iops: '8192',
			os: 'Linux',
			distro: 'CloudLinux 8.8+',
			architecture: 'x86_64',
			php: '8.3+',
			pear: true,
			nodejs: '20.3+',
			npm: true,
			python: '3.11+',
			pip: true,
			ruby: '3.11+',
			gem: true,
			perl: '5.26+',
			cpan: true,
			mysql: '8.3+',
			mariadb: '10.3+',
			phpmyadmin: true,
			terminal: false,
			ssh: true,
			git: true,
			metrics: true,
			security: true,
			virusScanner: true,
			softaculous: true,
			wordpress: true,
			backup: 'Daily',
		},
		button: {
			text: 'Order Now',
			link: 'https://cpanel.stechbd.net/store/reseller-hosting/100gb',
		},
	},
]
